language: node_js
node_js:
  - "10"
env:
  - GH_PAGES_SRC="packages/apps/build"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - if [ "$TRAVIS_BRANCH" === "next" ]; then UI_THEME=substrate yarn polkadot-dev-build-travis; else UI_THEME=polkadot yarn polkadot-dev-build-travis; fi
